import { users, userFollows } from "./users";
import {
  showcases,
  showcaseImages,
  showcaseTags,
  showcaseLikes,
} from "./showcases";
import { comments, commentLikes, downloads, purchases } from "./interactions";
import { collections, collectionShowcases, reports } from "./community";
import { notifications } from "./notifications";
import {
  usersRelations,
  showcaseImagesRelations,
  showcaseLikesRelations,
  showcaseTagsRelations,
  showcasesRelations,
  commentsRelations,
  commentLikesRelations,
  purchasesRelations,
  downloadsRelations,
  collectionsRelations,
  collectionShowcasesRelations,
  reportsRelations,
  notificationsRelations,
  userFollowsRelations,
  categoriesRelations,
  tagsRelations,
  curatedShowcasesRelations,
  curatedCollectionsRelations,
} from "./relations";
import { categories, tags } from "./content";
import { curatedShowcases, curatedCollections } from "./curations";

export const schema = {
  // tables
  users,
  userFollows,
  usersRelations,
  showcases,
  showcaseImages,
  showcaseTags,
  showcaseLikes,
  comments,
  commentLikes,
  downloads,
  purchases,
  collections,
  collectionShowcases,
  notifications,
  reports,
  categories,
  tags,
  curatedShowcases,
  curatedCollections,
  // relations
  showcaseImagesRelations,
  showcaseLikesRelations,
  showcaseTagsRelations,
  showcasesRelations,
  commentsRelations,
  commentLikesRelations,
  purchasesRelations,
  downloadsRelations,
  collectionsRelations,
  collectionShowcasesRelations,
  reportsRelations,
  notificationsRelations,
  userFollowsRelations,
  categoriesRelations,
  tagsRelations,
  curatedShowcasesRelations,
  curatedCollectionsRelations,
} as const;

export {
  // tables
  users,
  userFollows,
  usersRelations,
  showcases,
  showcaseImages,
  showcaseTags,
  showcaseLikes,
  comments,
  commentLikes,
  downloads,
  purchases,
  collections,
  collectionShowcases,
  notifications,
  reports,
  categories,
  tags,
  curatedShowcases,
  curatedCollections,
  // relations
  showcaseImagesRelations,
  showcaseLikesRelations,
  showcaseTagsRelations,
  showcasesRelations,
  commentsRelations,
  commentLikesRelations,
  purchasesRelations,
  downloadsRelations,
  collectionsRelations,
  collectionShowcasesRelations,
  reportsRelations,
  notificationsRelations,
  userFollowsRelations,
  categoriesRelations,
  tagsRelations,
  curatedShowcasesRelations,
  curatedCollectionsRelations,
};
